"""
PDF to Markdown converter using PaddleOCR-VL (Vision-Language Model).

Uses PaddleOCR-VL-1.5 (0.9B parameter VLM) which reads documents visually,
bypassing traditional table cell detection. Better for complex/dense tables.

=== Dependencies (install before running) ===

  CPU inference (default):
    pip install "paddlepaddle>=3.0.0" "paddleocr[doc-parser]" Pillow transformers

  GPU inference (--gpu flag):
    pip install "paddlepaddle-gpu>=3.0.0" "paddleocr[doc-parser]" Pillow transformers

  Notes:
    - Python 3.8–3.11 recommended (PaddlePaddle may not support 3.12+ yet).
    - On first run, PaddleOCR-VL downloads ~1–2 GB of model weights automatically.
    - The 'transformers' engine also requires a HuggingFace-compatible environment;
      HF_ENDPOINT is already configured below for mirror support.
    - For GPU, install the CUDA-matched paddlepaddle-gpu wheel from:
      https://www.paddlepaddle.org.cn/install/quick

=== Output layout ===

  <output_dir>/<pdf_stem>/
    ├── <pdf_stem>.md          final concatenated markdown
    ├── processing_time.txt    time taken to process the PDF
    ├── pages/                 per-page markdown files (page_001.md, page_002.md, …)
    │   └── imgs/              per-page embedded images (generated by PaddleOCR)
    ├── layout/                layout-detection visualisations (one image per page)
    └── json/                  per-page structured JSON results
"""

import argparse
import os
import sys
import time
from pathlib import Path

# ── PaddlePaddle / PaddleOCR environment ──────────────────────────────────────
os.environ.setdefault("PADDLE_PDX_PDF_RENDER_SCALE", "6.0")
os.environ.setdefault("PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK", "True")

# HuggingFace mirror (useful in regions with restricted access)
os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
os.environ.setdefault("HUGGINGFACE_HUB_CACHE", os.path.expanduser("~/.cache/huggingface"))
os.environ.setdefault("HF_HUB_DOWNLOAD_TIMEOUT", "300")

# Disable SSL verification (some corporate proxies use self-signed certs)
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
os.environ["CURL_CA_BUNDLE"] = ""
os.environ["REQUESTS_CA_BUNDLE"] = ""
os.environ["SSL_CERT_FILE"] = ""
# ──────────────────────────────────────────────────────────────────────────────


def convert_pdf_to_markdown(
    input_pdf: str,
    output_dir: str = "./output",
    use_doc_orientation_classify: bool = False,
    use_doc_unwarping: bool = False,
    use_layout_detection: bool = True,
    device: str = "cpu",
) -> Path:
    """
    Convert a PDF file to Markdown using PaddleOCR-VL (Vision-Language Model).

    Args:
        input_pdf:                    Path to the input PDF file.
        output_dir:                   Directory where output is saved.
        use_doc_orientation_classify: Auto-rotate pages based on detected orientation.
        use_doc_unwarping:            Apply document unwarping (de-skew).
        use_layout_detection:         Enable layout analysis and ordering.
        device:                       Inference device: "cpu" or "gpu".

    Returns:
        Path to the output directory for this PDF.
    """
    try:
        from paddleocr import PaddleOCRVL
    except ImportError:
        print(
            "ERROR: PaddleOCR is not installed.\n"
            "Run: pip install paddlepaddle \"paddleocr[doc-parser]\""
        )
        sys.exit(1)

    input_path = Path(input_pdf).resolve()
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        sys.exit(1)
    if input_path.suffix.lower() != ".pdf":
        print(f"ERROR: Input file must be a PDF. Got: {input_path.suffix}")
        sys.exit(1)

    output_path = Path(output_dir).resolve() / input_path.stem
    pages_dir  = output_path / "pages"
    json_dir   = output_path / "json"
    layout_dir = output_path / "layout"
    for d in (output_path, pages_dir, json_dir, layout_dir):
        d.mkdir(parents=True, exist_ok=True)

    # ── Load pipeline ──────────────────────────────────────────────────────────
    print(f"[1/4] Loading PaddleOCR-VL pipeline (device={device}, engine=transformers) ...")
    pipeline = PaddleOCRVL(
        device=device,
        engine="transformers",
        use_doc_orientation_classify=use_doc_orientation_classify,
        use_doc_unwarping=use_doc_unwarping,
        use_layout_detection=use_layout_detection,
    )

    # Start global processing timer
    start_time = time.time()

    # ── Run inference page-by-page ─────────────────────────────────────────────
    print(f"[2/4] Processing PDF page-by-page: {input_path}")
    print("      Outputs for each page will be saved immediately as they finish.")
    
    # predict() returns a generator stream
    pages_iterator = pipeline.predict(input=str(input_path))
    accumulated_pages = []

    for page_idx, res in enumerate(pages_iterator, start=1):
        page_start = time.time()
        print(f"   → Processing page {page_idx:03d}...")

        # 1. Save structured JSON immediately
        res.save_to_json(save_path=str(json_dir / f"page_{page_idx:03d}.json"))

        # 2. Save layout visualisation immediately
        try:
            res.save_to_img(save_path=str(layout_dir))
        except Exception as e:
            print(f"      WARNING: layout image for page {page_idx} could not be saved: {e}")

        # 3. Save Markdown text + images immediately
        res.save_to_markdown(save_path=str(pages_dir / f"page_{page_idx:03d}.md"))
        
        page_elapsed = time.time() - page_start
        print(f"      ✓ Page {page_idx:03d} saved successfully ({page_elapsed:.2f}s)")
        
        # Collect results in memory for the final document stitching
        accumulated_pages.append(res)

    if not accumulated_pages:
        print("ERROR: No pages were processed. Is the PDF valid and non-empty?")
        sys.exit(1)

    # ── Restructure ────────────────────────────────────────────────────────────
    print(f"\n[3/4] Restructuring all {len(accumulated_pages)} page(s) (cross-page layout optimization) ...")
    restructured = pipeline.restructure_pages(
        accumulated_pages,
        merge_tables=True,
        relevel_titles=True,
        concatenate_pages=True,
    )

    # ── Save final concatenated output ─────────────────────────────────────────
    print("[4/4] Saving final concatenated markdown ...")
    for res in restructured:
        res.save_to_markdown(
            save_path=str(output_path / f"{input_path.stem}.md")
        )

    # Stop global timer and record metrics
    end_time = time.time()
    elapsed_seconds = end_time - start_time
    minutes, seconds = divmod(elapsed_seconds, 60)
    
    time_log_path = output_path / "processing_time.txt"
    with open(time_log_path, "w") as f:
        f.write(f"File: {input_path.name}\n")
        f.write(f"Pages: {len(accumulated_pages)}\n")
        f.write(f"Device: {device}\n")
        f.write(f"Total processing time: {elapsed_seconds:.2f} seconds ({int(minutes)}m {seconds:.2f}s)\n")

    print(f"\n✅ Done! All outputs are ready inside: {output_path}")
    print(f"   ⏱️  Total Time: {int(minutes)}m {seconds:.2f}s")
    print(f"   ├── {input_path.stem}.md         (final merged markdown)")
    print(f"   ├── processing_time.txt (timing details)")
    print(f"   ├── pages/              (individual files, written on-the-fly)")
    print(f"   ├── layout/             (layout visualizations, written on-the-fly)")
    print(f"   └── json/               (structured layout data, written on-the-fly)")
    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Convert a PDF to Markdown using PaddleOCR-VL (Vision-Language Model)."
    )
    parser.add_argument(
        "input_pdf",
        help="Path to the input PDF file.",
    )
    parser.add_argument(
        "-o", "--output-dir",
        default="./output",
        help="Directory to save the output (default: ./output).",
    )
    parser.add_argument(
        "--gpu",
        action="store_true",
        help="Use GPU for inference (requires paddlepaddle-gpu).",
    )
    parser.add_argument(
        "--orientation",
        action="store_true",
        help="Enable automatic page orientation detection and correction.",
    )
    parser.add_argument(
        "--unwarp",
        action="store_true",
        help="Enable document unwarping (de-skew).",
    )
    parser.add_argument(
        "--no-layout",
        action="store_true",
        help="Disable layout analysis and ordering module.",
    )

    args = parser.parse_args()

    convert_pdf_to_markdown(
        input_pdf=args.input_pdf,
        output_dir=args.output_dir,
        use_doc_orientation_classify=args.orientation,
        use_doc_unwarping=args.unwarp,
        use_layout_detection=not args.no_layout,
        device="gpu" if args.gpu else "cpu",
    )


if __name__ == "__main__":
    main()